### ISSUE TITLE
Give me a way to go non-interactive

### ISSUE THREAD

**Issue by dabrahams** [paulaltin/git-subline-merge#5]
I've gotten to the point of confidence with this wonderful tool that I'd like git merge to just attempt to subline-merge every hunk and accept it automatically if it works, leaving only the ones that fail as merge conflicts.  The whole "what do you want to do with this hunk" interaction gets in the way.  Can I have a way to turn it off?

Thanks!

**Comment by paulaltin** [comment]
Wow, even I haven't got to that point yet! But yes, that should be doable. I don't think there's a way to pass arguments in to a custom merge driver, but if you don't mind setting an environment variable to control this behavior I can check for that in the script (you'd have to set it e.g. in your bashrc).

**Comment by paulaltin** [comment]
OK, I've pushed a branch called `non-interactive` which should do what you want. You can either set the environment variable `GIT_SUBLINE_MERGE_NON_INTERACTIVE_MODE` (e.g. `export GIT_SUBLINE_MERGE_NON_INTERACTIVE_MODE=1` in your bashrc, or just on an ad-hoc basis) or change the value on line 44 of the script to `True`.

Would you like to try it out and let me know whether it works?

**Comment by dabrahams** [comment]
Holy convenience, Batman, that's awesome!  Now I can go back to having it on as my default merge method, and it doesn't cause a problem for magit.  The one thing I do notice is a whole bunch of empty lines in the output when it gets invoked during a merge.

**Comment by paulaltin** [comment]
Glad it works for you!

Do you mean empty lines in the merged files, or in the command line output?

**Comment by dabrahams** [comment]
In the command line output.

**Comment by paulaltin** [comment]
OK, I'll take a look. Thanks!

**Comment by paulaltin** [comment]
OK, I think the empty lines should be gone now.

**Comment by paulaltin** [comment]
@dabrahams: are you happy for me to merge the `non-interactive` branch?

**Comment by dabrahams** [comment]
Yes, please merge it!

**Comment by dabrahams** [comment]
I just changed a colleague's life by showing this to him.  The non-interactive thing meant GSM was resolving hundreds of conflicts and he was left with 3, which he could easily handle by hand.  I (seriously!) think you should make this the default mode.

One other thing you should do, IMO, is deal with the "pip install future" thing up-front in the README.  Lots of people develop on Macs, which only have Python 2.7, and if they run into that problem they will usually not get any further with GSM.

**Comment by paulaltin** [comment]
I'm glad it's so useful for him! And thanks for helping to spread the word :)

I am still quite reluctant to make non-interactive mode on by default. Personally I would never use it that way, because the subline merge does sometimes get it wrong. It's particularly dangerous when it manages to generate code that is incorrect but still compiles, possibly resulting in a very hard-to-find bug. It doesn't happen often (I've seen it maybe two or three times out of hundreds of subline merges), but the potential consequences are serious enough for me to want to err on the side of safety here. Now that we have an option to go non-interactive, I'd prefer to force people to use it interactively first until they understand how it works, and then they can make an eyes-open decision about how much they want to trust it in their own development.

Having said all that, I'm interested in your use case and how you can be so confident that it will always do the right thing. Are your conflicts somehow predictable, e.g. do they arise in automatically generated code? (I understand if you can't say.)

**Comment by paulaltin** [comment]
Also, I've added a note to the installation instructions in the README for Python 2 users as you suggested. Thanks for the feedback!

**Comment by dabrahams** [comment]
> On May 15, 2019, at 8:46 PM, paulaltin <notifications@github.com> wrote:
> 
> Having said all that, I'm interested in your use case and how you can be so confident that it will always do the right thing. Are your conflicts somehow predictable, e.g. do they arise in automatically generated code? (I understand if you can't say.)
> 

I am not so confident, but we do have tests, which help mitigate the risk.  I can say, however, that some of these merges would simply have taken an untenable amount of work to complete if we had to inspect and approve each subline merge.

**Comment by paulaltin** [comment]
OK, fair enough.

Out of respect for some kind of "least harm" principle, I think I'd still prefer to keep the non-interactive mode as opt-in rather than opt-out. I hope you understand..

**Comment by dabrahams** [comment]
Of course I do!

**Comment by paulaltin** [comment]
Cool :) Thanks again for all your feedback!
